# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v3.2.1-3-ga2a82bc
_src_path: gh:klaasnicolaas/pypackage-template
author_email: klaas@mrgreenoffices.nl
author_name: Klaas Schoute
github_sponsors: false
github_username: klaasnicolaas
kofi_funding: false
package_name: balena_cloud
project_name: Balena Cloud
project_short_description: ''
project_slug: balena-cloud
run_poetry_install: false
software_license: MIT License
tweet_on_release: false
